services:
  webapp:
    image: webapp
    build:
      context: .
      dockerfile: src/Notissimus/WebApp/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - Database

  Database:
    image: postgres:latest
    environment:
      POSTGRES_DB: Database
      POSTGRES_USER: User
      POSTGRES_PASSWORD: qwe123asd
    ports:
      - "6000:5432"